AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/*'

# Documentation will or will not be added on whim
Documentation:
  Enabled: false

# Disable all metrics.
Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: new_line

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceBeforeSemicolon:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false


# Whens are empty even with comments
Lint/EmptyWhen:
  Enabled: false

# Allow extra parameters
Lint/UnusedMethodArgument:
  Enabled: false

# Allow extra parameters
Lint/UnusedBlockArgument:
  Enabled: false

# Allow 'Pokémon-style' exception handling
Lint/RescueException:
  Enabled: false

# http://stackoverflow.com/questions/4763121/should-i-use-alias-or-alias-method
Style/Alias:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: false

Style/BlockComments:
  Enabled: false

# Prefer compact module/class defs
Style/ClassAndModuleChildren:
  Enabled: false

# Allow CamelCase constants as well as SCREAMING_SNAKE_CASE
Naming/ConstantName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

# I don't understand this one
Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: false

# Allowing JavaScript-esque chaining
Style/MultilineBlockChain:
  Enabled: false

# Prefer |m, e| for the `reduce` block arguments
Style/SingleLineBlockParams:
  Methods:
    - reduce: [m, e]
    - inject: [m, e]

# Allow % quoting
Style/UnneededPercentQ:
  Enabled: false

# Ignore `eval` in the examples folder
Security/Eval:
  Exclude:
    - src/commands/eval.rb
